version: "3"

services:
  mysql:
    container_name: billy-mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=billy
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./var/mysql:/var/lib/mysql
    networks:
      - database
    cap_add:
      - SYS_NICE
    profiles:
      - "billy"
      - "backend"
      - "db"
      - "migration"

  backend:
    container_name: billy-backend
    environment:
      - MYSQL_USER=user
      - MYSQL_PW=password
      - MYSQL_DB=billy
      - MYSQL_SERVER=mysql
      - MYSQL_PORT=3306
    build: .
    networks:
      - database
    ports:
      - "5000:5000"
    depends_on:
      - "mysql"
    profiles:
      - "billy"
      - "backend"

  frontend:
    container_name: billy-frontend
    build: frontend
    ports:
      - "3000:80"
    profiles:
      - "billy"
      - "frontend"

  migration:
    container_name: billy-migration
    environment:
      - MYSQL_USER=user
      - MYSQL_PW=password
      - MYSQL_DB=billy
      - MYSQL_SERVER=mysql
      - MYSQL_PORT=3306
    build: .
    volumes:
      - ".:/usr/src/app"
    networks:
      - database
    depends_on:
      - "mysql"
    profiles:
      - "migration"

networks:
  database:
