version: "3"

services:
  mysql:
    container_name: billy-mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=billy
    ports:
      - "5432:5432"
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  billy:
    container_name: billy
    environment:
      - MYSQL_USER=user
      - MYSQL_PW=password
      - MYSQL_DB=billy
      - MYSQL_SERVER=mysql
      - MYSQL_PORT=5432
      - BANK_IBAN=CH4431999123000889012
      - BANK_REF_PREFIX=123456
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "mysql"
