version: "3"

services:
  mysql:
    container_name: billy-mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=billy
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    ports:
      - "3306:3306"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
  backend:
    container_name: billy-backend
    environment:
      - MYSQL_USER=user
      - MYSQL_PW=password
      - MYSQL_DB=billy
      - MYSQL_SERVER=mysql
      - MYSQL_PORT=3306
      - BANK_IBAN=CH4031000039529071000
      - BANK_REF_PREFIX=123456
      - OAUTHLIB_INSECURE_TRANSPORT=true
      - REDIRECT_URL_LOGIN=http://localhost:3000/gruezzi
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "mysql"
