"""recent email

Revision ID: a79b833f15e9
Revises: f9af6c32a844
Create Date: 2021-08-01 13:26:49.739159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79b833f15e9'
down_revision = 'f9af6c32a844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('last_email_sent', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'last_email_sent')
    # ### end Alembic commands ###
